### ISSUE TITLE
Should we ship this? 

### ISSUE THREAD

**Issue by HenrikJoreteg** [AmpersandJS/ampersand-events#1]
I think it's pretty much ready to go. Can I get some review from @AmpersandJS/core-team so we can ship it?

**Comment by wraithgar** [comment]
Readme looks good.  Tests do not run for me locally.

**Comment by HenrikJoreteg** [comment]
@wraithgar i blew away node modules, reinstalled, and they ran just fine. What errors are you seeing?

**Comment by wraithgar** [comment]
Mine was a clean clone + npm i :shrug:

I make it run tests like the other repose (node test | tap-spec) and left the test-ci/browser lines alone.  If we want to change how we do tests let's, otherwise this is a +1 from me it all looks good now.

**Comment by HenrikJoreteg** [comment]
ok, once i get travis to run properly, i'll publish `1.0.0` and add it to the docs site.

**Comment by kamilogorek** [comment]
Code looks fine, tests run correctly as well. Clean clone, npm install, npm test. +1

**Comment by HenrikJoreteg** [comment]
Oh good! Because we already did. Lol
